In [3]:
import numpy as np

# 1. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
# 2. Write a NumPy program to reverse an array (the first element becomes the last).
arr = [12,13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]
print(arr[::-1])

[37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12]


In [9]:
# 3. Write a NumPy program to convert an array to a floating type.
int_array = np.array([1, 2, 3, 4, 5])
float_arr = int_array.astype(float)
print(float_arr)

[1. 2. 3. 4. 5.]


In [6]:
# 4. Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

result1 = np.add(array1, array2)

result2 = array1 + array2

print("Result using np.add():")
print(result1)

print("\nResult using + operator:")
print(result2)

Result using np.add():
[[ 8 10 12]
 [14 16 18]]

Result using + operator:
[[ 8 10 12]
 [14 16 18]]


In [7]:
# 5. From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 4, 3, 8, 10])
match = np.where(array1 == array2)
print(match)

(array([2], dtype=int64),)
